server:
  port: ${PORT:8080}
logging:
  level:
    org:
      springframework:
        security: DEBUG
      arun: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/
