spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
swagger:
  exclude: gateway,configuration-server,edge
---
server:
  port: ${PORT:7081}
spring:
  profiles: dev
---
spring:
  profiles: stage
---
spring:
  profiles: prod
---
