spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      retry:
        enabled: false
  main:
    allow-bean-definition-overriding: true
swagger:
  exclude: gateway,configuration-server,edge
---
server:
  port: ${PORT:7080}
spring:
  profiles: dev
---
spring:
  profiles: stage
---
spring:
  profiles: prod
---
