server:
  port: ${PORT:7081}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      retry:
        enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/
swagger:
  exclude: gateway,configuration-server
