server:
  port: ${PORT:9935}
spring:
  datasource:
    continue-on-error: true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      org:
      hibernate:
        default_schema: merchant
        ddl-auto: update
        hbm2ddl:
          auto:
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    generate-ddl: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://unipetdbserver.database.windows.net:1433;databaseName=unipetdb
    username: bsunipet
    password: BS@Dhaka
---
spring:
  profiles: stage
  datasource:
    url: jdbc:sqlserver://unipetdbserver.database.windows.net:1433;databaseName=unipetdb
    username: bsunipet
    password: BS@Dhaka
---
spring:
  profiles: prod
  datasource:
    url: jdbc:sqlserver://unipetdbserver.database.windows.net:1433;databaseName=unipetdb
    username: bsunipet
    password: BS@Dhaka
---
